
site_name: Sample Document
site_description: Sample Document, Japanese version
site_author: ttakayuki
nav:
  - 'Sample Document 日本語版': 'https://ttakayuki.github.io/my-pages/ja/'
theme:
  name: 'material'
  favicon: 'img/favicon.png'
  logo: 'img/logo.png'
  palette:
    primary: 'red'
markdown_extensions:
  - admonition
plugins:
  - redirects:
      redirect_maps:
        'index.md': 'https://ttakayuki.github.io/my-pages/ja/'
