name: Validate Pull Request Source

on:
  pull_request:
    branches:
      - main
      - master

jobs:
  validate_pr_source:
    runs-on: ubuntu-latest
    steps:
      - name: Check source branch
        env:
          BRANCH_NAME: ${{ github.head_ref }}
        if: ! startswitdh(env.BRANCH_NAME, 'devel-')
        run: exit 1
