name: Validate Pull Request Source

on:
  pull_request:
    branches:
      - main
      - master

jobs:
  validate_pr_source:
    env:
      BRANCH_NAME: ${{ github.head_ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Check source branch
        if: ! startsWith(env.BRANCH_NAME, 'devel-')
        run: |
          echo "Unexpected pull request source ${BRANCH_NAME}"
          exit 1
      - name: Check OK
        run: echo "Expected branch source was specified."

